# Generated by Django 4.1.7 on 2023-03-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_post_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
