# Generated by Django 4.1.7 on 2023-03-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
