# Generated by Django 4.1.7 on 2023-03-17 09:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_post_content_alter_post_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='İçerik'),
        ),
    ]
